In [16]:
## from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

classifier=Sequential()

classifier.add(Conv2D(32,(3,3),input_shape=(64,64,3),activation='relu'))

classifier.add(MaxPooling2D(pool_size=(2,2)))

classifier.add(Conv2D(32,(3,3),activation='relu'))

classifier.add(MaxPooling2D(pool_size=(2,2)))

classifier.add(Flatten())

classifier.add(Dense(units = 128, activation = 'relu')) 

classifier.add(Dense(units = 1, activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



In [17]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,shear_range = 0.2, zoom_range = 0.2, horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('/Users/naubergois/Downloads/Convolutional_Neural_Networks/dataset/training_set',
target_size = (64, 64), batch_size = 32, class_mode = 'binary')

test_set = train_datagen.flow_from_directory('/Users/naubergois/Downloads/Convolutional_Neural_Networks/dataset/test_set',
target_size = (64, 64), batch_size = 32, class_mode = 'binary')







Found 8000 images belonging to 2 classes.
Found 2000 images belonging to 2 classes.


In [ ]:
classifier.fit_generator(training_set, steps_per_epoch = 8000,epochs = 5, validation_data = test_set, validation_steps = 20)

Epoch 1/5
 100/8000 [..............................] - ETA: 8109s - loss: 0.6601 - acc: 0.6009

In [23]:
import numpy as np
from keras.preprocessing import image

test_image = image.load_img('/Users/naubergois/Downloads/Convolutional_Neural_Networks/dataset/single_prediction/cachorro_desenho.jpg', target_size = (64, 64))

test_image = image.img_to_array(test_image) 
test_image = np.expand_dims(test_image, axis = 0) 
print(test_image)
result = classifier.predict(test_image)
print(result)

[[[[ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   ..., 
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]]

  [[ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   ..., 
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]]

  [[ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   ..., 
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]]

  ..., 
  [[ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   ..., 
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]]

  [[ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   ..., 
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]]

  [[ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   ..., 
   [ 255.  255.  255.]
   [ 255.  255.  255.]
   [ 255.  255.  255.]]]]
[[ 1.]]
